#!/bin/sh
# This is an example of using command line arguments.
# To use this script, type ./scriptarg arg1 arg2 arg3 ... argn
# Then it will list out the arguments on separate lines
echo "Number of arguments: $#"
echo "\$0 = $0"

echo "Loop over \$*"
for a in $* 
do
   echo \"$a\"
done



